# -*- coding: utf-8 -*-
"""Zuev_Maksim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gmH5yZkr9WVCug3b_FZy1t8yl0jdyKfx
"""

#Задача 44
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
#data.head()
#********************************************************
data['abc'] = 1 # Присваиваем значение '1'
data.set_index([data.index, 'whoAmI'], inplace=True) # индекс фрейма данных, используя существующие столбцы.
data = data.unstack(level=-1, fill_value = 0).astype(int) #"сводим" уровень индекса строки к оси столбца со значением '0'
data.columns = data.columns.droplevel() # Метод droplevel фрейма данных Pandas()
data.columns.name = None
data.head()